import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '600'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Next Gen Academy",
  description: "Generated by Next Gen Academy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased "font-roboto"`}
      >
        <Navbar />
        {children}
         <Toaster
          position="top-center"
          toastOptions={{
            duration: 5000,
          }}
        />
        <Footer />
      </body>
    </html>
  );
}
